#!/bin/sh
VERSION=v0.44.1

load() {

make -f - <<EOF

load: nwjs-sdk-${VERSION}-linux-x64.tar.gz
	tar -xzf $<

nwjs-sdk-${VERSION}-linux-x64.tar.gz:
	wget -vc https://dl.nwjs.io/${VERSION}/nwjs-sdk-${VERSION}-linux-x64.tar.gz
EOF
}

[ -f */nw ] &&  exec */nw ../ArduinoviewJsServ || load && exec */nw ../ArduinoviewJsServ
